### ISSUE TITLE
How to detect if gerrit connection is alive?

### ISSUE THREAD

**Issue by psumitb** [sonyxperiadev/gerrit-events#56]
I just wanted to know that after I make connection to the gerrit server, how can i find if the connection has really established or not. Sometimes when I run my program, if Gerrit has not started, I am not able to find that. Is there a way to do that after I try to establish a connection.

**Comment by rsandell** [comment]
https://github.com/sonyxperiadev/gerrit-events/blob/master/src/main/java/com/sonymobile/tools/gerrit/gerritevents/ConnectionListener.java
https://github.com/sonyxperiadev/gerrit-events/blob/master/src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnection.java#L261

**Comment by psumitb** [comment]
Hello,
I tried adding the listener to the GerritConnection but it's not working.
I also found that when connect function of GerritConnection is called, it goes to infinite loop. If there is no running Gerrit Server than `ssh=SshConnectionFactory.getConnection()` function raises an exception and the variable ssh is still null. Beacuse of this, the disconnect function is not called and infinite loop goes on.

**Comment by rsandell** [comment]
Yes, that is by design, it will try to connect and reconnect until it can
or shutdown(boolean join) is called.

/B

On Mon, Jul 4, 2016 at 6:57 AM, psumitb <notifications@github.com> wrote:

> Hello,
> I tried adding the listener to the GerritConnection but it's not working.
> I also found that when connect function of GerritConnection is called, it
> goes to infinite loop. If there is no running Gerrit Server than
> ssh=SshConnectionFactory.getConnection() function raises an exception and
> the variable ssh is still null. Beacuse of this, the disconnect function is
> not called and infinite loop goes on.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/sonyxperiadev/gerrit-events/issues/56#issuecomment-230204999>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AASWkBpw5CIDiCki5JK4a9V4Zb8cgqgLks5qSJKrgaJpZM4JDItz>
> .
>



-- 
Robert Sandell
*Software Engineer*
*CloudBees Inc.*
